---
title: "CS_final"
author: "Issac Li"
date: "12/30/2016"
output: 
  html_document:
    fig_width: 8
    fig_height: 10
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 2a
```{r echo=FALSE}
set.seed(180)

mm <- read.csv("/Users/lizhuo/Downloads/mm.csv")
vpi=vector('double',100)+0.5

compute_T<-function(vz,vy,vpi){
  n=length(vz)
  T_test=1/n*sum((vy*vz)/vpi-vy*(1-vz)/(1-vpi))
  T_test
}

t=compute_T(mm$z,mm$y,vpi)
paste("Test statistics is:", t)
```
## 2b
### Part 1 Use Newtown Method to find lambda
```{r echo=FALSE, warnings = FALSE}
tau=0  

y0=ifelse(mm$z,mm$y-tau,mm$y)
y1=ifelse(mm$z,mm$y,mm$y+tau)

calc_a <-function(y0,vpi){
  1/NROW(y0)*rowSums(y0%*%(1/(vpi-1)))
}

calc_vb <-function(y0,y1,vpi,vz){
  1/NROW(vz)*(y1%*%diag(1/vpi)+y0%*%diag(1/(1-vpi)))
}

a=calc_a(y0,vpi)
vb=calc_vb(y0,y1,vpi,mm$z)

f<-function(lam,vpi,a,vb,t){
  a-t+sum((vpi*vb*exp(lam*vb))/(vpi*exp(lam*vb)-vpi+1))
}

gradient <- function(lam,vpi,a,vb){
  sum(-1*(vpi-1)*vpi*vb^2*exp(vb*lam)/(vpi*exp(vb*lam)-vpi+1)^2)
}

IssacNewton <- function(y,z,vpi,t,tau,a,vb,lam0,iter_max,delta) {
  y0=ifelse(mm$z,mm$y-tau,mm$y)
  y1=ifelse(mm$z,mm$y,mm$y+tau)
  a=calc_a(y0,vpi)
  vb=calc_vb(y0,y1,vpi,mm$z)
  iter = 0
  while(iter<iter_max){
    lam1=lam0-f(lam0,vpi,a,vb,t)/gradient(lam0,vpi,a,vb)
    iter=iter+1
    if ((abs(lam0-lam1))<=delta){
      break
    }
    lam0=lam1
  }
  lam0
}

lam=IssacNewton(mm$y,mm$z,vpi,t=t,tau=0,a=a,vb=vb,lam0=1,iter_max = 1000,1e-6)
paste("The lambda that minimizes P_bound is: ",round(lam,3))
```

### Part 2 find p2
```{r echo=FALSE}
compute_Tt<-function(wi,y0,y1,vpi){
  n=dim(wi)[2]
  T_test=1/n*rowSums(t(apply(wi,1,function(x) (y1*x)/0.5-y0*(1-x)/(1-0.5))))
  T_test
}

p2 <-function(tau,vpi,lam,t,M){
  y0=ifelse(mm$z,mm$y-tau,mm$y)
  y1=ifelse(mm$z,mm$y,mm$y+tau)
  a=calc_a(y0,vpi)
  vb=calc_vb(y0,y1,vpi,mm$z)
  pwi=(exp(lam*vb)*vpi)/(exp(lam*vb)*vpi+1-vpi)
  wj=matrix(NA,nrow = M,ncol=100)
  for(i in 1: M){
    wj[i,]=rbinom(100,1,pwi)
  }
  Tt=compute_Tt(wi=wj,y0=y0,y1=y1,vpi = vpi)
  exp(lam*a)*prod(exp(lam*vb)*vpi+1-vpi)/M*sum(ifelse(Tt>=t,1,0)*exp(-lam*Tt))
}

p2bar=p2(tau = 0,vpi,lam=lam,t,M=1000)

paste("The computed estimate is: ", round(p2bar,8))
```


### Part 3 explain choice of M
```{r echo=FALSE,message=FALSE}
b2=matrix(NA,nrow=3,ncol=2,byrow = TRUE)

M=10
p2bar<-p2(tau = 0,vpi,lam=lam,t=t,M=M)
var_ub<- 1/M*(exp(2*lam*(a-t))*prod((exp(lam*vb)*vpi+1-vpi)^2)-p2bar)

b2[1,1]=M
b2[1,2]=round(abs((var_ub)/p2bar),3)*100

M=100
p2bar<-p2(tau = 0,vpi,lam=lam,t=t,M=M)
var_ub<- 1/M*(exp(2*lam*(a-t))*prod((exp(lam*vb)*vpi+1-vpi)^2)-p2bar)

b2[2,1]=M
b2[2,2]=round(abs((var_ub)/p2bar),3)*100

M=1000
p2bar<-p2(tau = 0,vpi,lam=lam,t=t,M=M)
var_ub<- 1/M*(exp(2*lam*(a-t))*prod((exp(lam*vb)*vpi+1-vpi)^2)-p2bar)
b2[3,1]=M
b2[3,2]=round(abs((var_ub)/p2bar),3)*100

colnames(b2)<-c("M","Var/P")
b2[,2]=paste(b2[,2],"%")
print(as.table(b2))
```

When M is 1000, the variance is small enough (<0.1% of the estimate).

## 2c
```{r echo=FALSE, message=FALSE, warning = FALSE}
set.seed(180)
pi=0.5
n=100
p0<-function(tau){
  y0=ifelse(mm$z,mm$y-tau,mm$y)
  y1=ifelse(mm$z,mm$y,mm$y+tau)
  v=(1/n^2)*sum(y1^2/pi+y0^2/(1-pi)-tau^2)
  Tt=(t-tau)/sqrt(v)
  return(1-pnorm(Tt))
}

p1<-function(tau,M){
  y0=ifelse(mm$z,mm$y-tau,mm$y)
  y1=ifelse(mm$z,mm$y,mm$y+tau)
  Tts=vector(mode = "logical",length=M)
  for(i in 1:M){
    wi=rbinom(100,1,1/2)
    Tt=(1/100)*sum(y1*wi/pi-y0*(1-wi)/(1-pi))
    Tts[i]=ifelse(Tt>=t,1,0)
  }
  sum(Tts)/M
}

plam<-function(tau,lam=34.65736){
  y0=ifelse(mm$z,mm$y-tau,mm$y)
  y1=ifelse(mm$z,mm$y,mm$y+tau)
  a=calc_a(y0,vpi)
  vb=calc_vb(y0,y1,vpi,mm$z)
  
  ifelse(tau<t,exp(lam*(a-t))*prod(0.5*exp(lam*vb)+1-0.5),1)
  
}

p2b <-function(tau,vpi,lam,t,M){
  y0=ifelse(mm$z,mm$y-tau,mm$y)
  y1=ifelse(mm$z,mm$y,mm$y+tau)
  a=calc_a(y0,vpi)
  vb=calc_vb(y0,y1,vpi,mm$z)
  pwi=(exp(lam*vb)*vpi)/(exp(lam*vb)*vpi+1-vpi)
  wj=matrix(NA,nrow = M,ncol=100)
  for(i in 1: M){
    wj[i,]=rbinom(100,1,pwi)
  }
  Tt=compute_Tt(wi=wj,y0=y0,y1=y1,vpi = vpi)
   if(tau<=t){
    return(exp(lam*a)*prod(exp(lam*vb)*vpi+1-vpi)/M*sum(ifelse(Tt>=t,1,0)*exp(-lam*Tt)))
   }
   if(tau>t){
    return(1-exp(lam*a)*prod(exp(lam*vb)*vpi+1-vpi)/M*sum(ifelse(Tt>=t,0,1)*exp(-lam*Tt)))
   }
}

trange=seq(-0.5,1.5,0.005)

p0bar=sapply(trange, p0)
p1bar=sapply(trange, p1,M=1000)

lams=c()
for (i in 1:length(trange)){
  lams=c(lams,IssacNewton(mm$y,mm$z,vpi,t=t,a=a,vb=vb,tau = trange[i],lam0=1,iter_max = 1000,delta=1e-6))
}

plbar=mapply(plam,tau=trange,lam=lams)
p2bar=mapply(p2,tau=trange,lam=lams,MoreArgs =  list(vpi=vpi,t=t,M=1000))
p2bar1=mapply(p2b,tau=trange,lam=lams,MoreArgs =  list(vpi=vpi,t=t,M=1000))

par(mfrow=c(3,1))
plot(trange,p0bar,ylim=c(0,1),type="l",col="grey",lty=1,lwd=2,xlab = "Tau",ylab="Est. Probability",
       main="Normal Appoximation, Upper Bound and Naive Estimator")
lines(trange,p1bar,ylim=c(0,1),col="blue",lty=1,lwd=1)
lines(trange,plbar,ylim=c(0,1),col="red",lty=5)
legend(-0.4,1.0,bty="n",y.intersp=1.5,
       c(expression(hat(p)[0]),expression(hat(p)[1]),expression(paste(tilde(p),list(tau,lambda)))),
       col=c("grey","blue","red"),lty=c(1,1,2),lwd=2)


plot(trange,p0bar,ylim=c(0,1),type="l",col="grey",lty=1,lwd=2,xlab = "Tau",ylab="Est. Probability",
       main="Normal Appoximation, Upper Bound and Tilted Estimator (1)")
lines(trange,plbar,ylim=c(0,1),col="red",lty=5)
lines(trange,p2bar,ylim=c(0,1),col="black",lty=1,lwd=1)
abline(v = 0.72,ylim=c(0,1),lty=2,col="grey")
legend(-0.4,1.0,bty="n",y.intersp=1.5,
       c(expression(hat(p)[0]),expression(paste(tilde(p),list(tau,lambda))),expression(paste(hat(p)[2])),"T=0.72"),
       col=c("grey","red","black","grey"),lty=c(1,2,1,2),lwd=2)

plot(trange,p0bar,ylim=c(0,1),type="l",col="grey",lty=1,lwd=2,xlab = "Tau",ylab="Est. Probability",
     main="Normal Appoximation, Upper Bound and Tilted Estimator (2)")
lines(trange,plbar,ylim=c(0,1),col="red",lty=5)
lines(trange,as.numeric(unlist(p2bar1)),ylim=c(0,1),col="black",lty=1,lwd=1)
abline(v = 0.72,lty=2,col="grey")
legend(-0.4,1.0,y.intersp=1.5,bty="n",
       c(expression(hat(p)[0]),expression(paste(tilde(p),list(tau,lambda))),expression(paste(hat(p)[2],"modified")),"T=0.72"),
         col=c("grey","red","black","grey"),lty=c(1,2,1,2),lwd=2)

```

In the middle panel, as we can see with Tau>t, the orginal tilted estimator breaks apart. This is because the chernoff bound only works with tail probability. So we flipped the distribution for Tau > t in the bottom panel. 

## 2d
```{r echo=FALSE}

p=p2bar
alpha=0.5
calc_CI<-function(p,alpha){
  inds=sort.list(p)[sort(p)>(alpha/2) & sort(p)<(1-alpha/2)]
  Tts=trange[inds]
  if(length(Tts)==0){
    return(c(0,0))
  }
  else{
    return(range(Tts))
  }
}

CI <- matrix(NA,nrow=4,ncol=4,byrow=TRUE)

CI[1,1:2]=calc_CI(p0bar,0.5)
CI[2,1:2]=calc_CI(p1bar,0.5)
CI[3,1:2]=calc_CI(plbar,0.5)
CI[4,1:2]=calc_CI(p2bar1,0.5)
CI[1,3:4]=calc_CI(p0bar,0.05)
CI[2,3:4]=calc_CI(p1bar,0.05)
CI[3,3:4]=calc_CI(plbar,0.05)
CI[4,3:4]=calc_CI(p2bar1,0.05)

colnames(CI) <- c("Lower 50%","Upper 50%","Lower 95%","Upper 95%")
rownames(CI) <- c("P_0","P_1","P_bound","P_2")
CI <- as.table(CI)
print(CI)
```
